apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workload
  name: workload-deployment 
  namespace: apolicy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: workload
  template:
    metadata:
      labels:
        app: workload
    spec:
      serviceAccountName: sa-apolicy
      containers:
        - name : workload
          image: local/workload
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: apolicy-secret
            - configMapRef:
                name: app-config 
          env:
            - name: DB_NAME
              value: apolicy
            - name: RESULTS_SUBSCRIPTION
              value: workload-result-sub
            - name: TASK_SUBSCRIPTION
              value: task-workload-sub
            - name: OPA_DATA_FILE
              value: /go/data.json
            - name: OPA_POLICY_FILE
              value: /go/policy.rego
---
apiVersion: v1
kind: Service
metadata:
  name: workload-service
  namespace: apolicy
spec:
  type: NodePort
  selector:
    app: workload
  ports:
    - port: 8081
      targetPort: 8081
